openapi: 3.0.3
info:
  title: Uniform Platform Aggregates Relationships API
  version: '2.0'
tags:
- name: Relationships
paths:
  /api/v1/relationships:
    get:
      description: Gets the relationships for a given entity type
      parameters:
      - schema:
          type: string
        required: true
        name: projectId
        in: query
      - schema:
          type: string
          enum:
          - component
          - contentType
          - blockType
          - asset
          - componentPattern
          - entryPattern
          - compositionPattern
          - entry
          - dataType
          - dataSource
          - test
        required: true
        name: type
        in: query
      - schema:
          type: array
          items:
            type: string
          minItems: 1
          description: Entity IDs
        required: true
        description: Entity IDs
        name: ids
        in: query
      - schema:
          type: boolean
          nullable: true
          default: false
          description: Whether to include a list of related instances in the response. Only supported when a single entity ID is provided
        required: false
        description: Whether to include a list of related instances in the response. Only supported when a single entity ID is provided
        name: withInstances
        in: query
      - schema:
          type: number
          minimum: 1
          maximum: 100
          description: Use this to paginate over the instances when "whenInstances" is true
        required: false
        description: Use this to paginate over the instances when "whenInstances" is true
        name: limit
        in: query
      - schema:
          type: number
          nullable: true
          minimum: 0
          description: Use this to paginate over the instances when "whenInstances" is true
        required: false
        description: Use this to paginate over the instances when "whenInstances" is true
        name: offset
        in: query
      responses:
        '200':
          description: 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    instances:
                      type: array
                      items:
                        type: object
                        properties:
                          uiStatus:
                            type: string
                            enum:
                            - Draft
                            - Modified
                            - Published
                            - Orphan
                            - Unknown
                            - Previous
                          publishedOnly:
                            type: boolean
                          icon:
                            type: string
                          instance:
                            type: object
                            properties:
                              _id:
                                type: string
                              _name:
                                type: string
                              _pattern:
                                type: string
                            required:
                            - _id
                            - _name
                            additionalProperties: false
                          edition:
                            type: object
                            properties:
                              id:
                                type: string
                              name:
                                type: string
                            required:
                            - id
                            - name
                            description: When set, this is a child edition of the instance in _id
                          pattern:
                            type: boolean
                          type:
                            type: string
                            enum:
                            - entry
                            - composition
                            - component
                          definition:
                            type: object
                            properties:
                              id:
                                type: string
                              name:
                                type: string
                            required:
                            - id
                            - name
                          release:
                            type: object
                            properties:
                              id:
                                type: string
                              name:
                                type: string
                            required:
                            - id
                            - name
                        required:
                        - publishedOnly
                        - instance
                        - pattern
                        - type
                        - definition
                        additionalProperties: false
                    totalCount:
                      type: number
                  required:
                  - id
                  - totalCount
                  additionalProperties: false
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '429':
          $ref: '#/components/responses/RateLimitError'
        '500':
          $ref: '#/components/responses/InternalServerError'
      tags:
      - Relationships
      security:
      - ApiKeyAuth: []
      - BearerAuth: []
components:
  responses:
    ForbiddenError:
      description: Permission was denied
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    RateLimitError:
      description: Too many requests in allowed time period
    BadRequestError:
      description: Request input validation failed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InternalServerError:
      description: Execution error occurred
    UnauthorizedError:
      description: API key or token was not valid
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    Error:
      type: object
      properties:
        errorMessage:
          description: Error message(s) that occurred while processing the request
          oneOf:
          - type: array
            items:
              type: string
          - type: string
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
    BearerAuth:
      type: http
      scheme: bearer
